anchor_scales:
- 4
- 8
- 16
- 32
base_model: attention
ckpt_path: null
cls_loss: focal
device: cuda
incomplete_iou_thresh: 0.3
incomplete_sample_ratio: 1.0
lambda_ctr: 1.0
lambda_reg: 5.0
log_file: log.txt
lr: 0.0001
max_epoch: 300
model: anchor-free
model_dir: models/fvs/
neg_iou_thresh: 0.0
neg_sample_ratio: 2.0
nms_thresh: 0.5
num_feature: 1024
num_head: 8
num_hidden: 128
pos_iou_thresh: 0.6
reg_loss: soft-iou
sample_rate: 15
save_path: null
seed: 12345
source: null
splits:
- ../splits/fvs.yml
weight_decay: 1.0e-05
